### ISSUE TITLE
Crash when setting all options under Max Display Num to 50

### ISSUE THREAD

**Issue by Jamesits** [15cm/AMM#5]
### What I Did

  1. Launch AMM
  2. Open Preferences
  3. Add a new server
  4. Set all "Max Display Num"s to 50
  5. Click OK
  6. Open Preferences again
  7. Change the content of any of Max Display Num textbox to another number
  8. Click on any other textbox

See screenshot below:
![image](https://cloud.githubusercontent.com/assets/1297257/22618612/d8b3fcdc-eb1b-11e6-923a-8da9fea23e09.png)

### Expected Behavior

AMM should let me save the changes and continue to work.

### Current Behavior

AMM crashes within 1 second. Clicking OK before it crash won't save the new value. 

### Application Log

```
Could not cast value of type 'AMM.TaskMenuItemSeperator' (0x102645ef8) to 'AMM.TaskMenuItem' (0x102645b50).
[1]    99465 abort      /Applications/AMM.app/Contents/MacOS/AMM
```

### Environment

  * macOS 10.12.4 Beta (16E144f)
  * AMM v0.1.0 (Build 170203_2)
  * Aria2 1.31.0
  * Bartender 2.1.6 (not sure if relevant, but it injects all app with a menubar icon)

**Comment by 15cm** [comment]
Fixed. Please download the latest release.

It was the problem of AMM itself.
